name: FOSS License Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  license-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install ScanCode Toolkit and dependencies
        run: |
          git clone https://github.com/nexB/scancode-toolkit.git
          cd scancode-toolkit
          pip install -r requirements.txt
          ./scancode --version

      - name: Run ScanCode
        run: |
          cd scancode-toolkit
          ./scancode --license --summary --classify --json-pp ../scan-output.json ../hello.py

      - name: Upload Scan Results
        uses: actions/upload-artifact@v4
        with:
          name: foss-scan-results
          path: scan-output.json
